<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Patronyme;
use App\Models\Region;
use App\Models\Province;
use App\Models\Commune;
use App\Models\GroupeEthnique;
use App\Models\Langue;
use App\Models\ModeTransmission;
use Carbon\Carbon;

class RealPatronymesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Données réelles de patronymes du Burkina Faso
        $patronymesData = [
            [
                'nom' => 'Ouédraogo',
                'signification' => 'Nom royal mossi signifiant "cheval de guerre"',
                'origine' => 'Royaume Mossi (Yatenga)',
                'histoire' => 'Patronyme des rois mossi du Yatenga. Selon la tradition, le premier roi Ouédraogo aurait été nommé ainsi car il est arrivé à cheval. Ce nom est porté par de nombreux chefs traditionnels mossi.',
                'region' => 'Nord',
                'province' => 'Yatenga',
                'commune' => 'Ouahigouya',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Cheval',
                'justification_totem' => 'Le cheval est l\'animal totem car le fondateur est arrivé à cheval',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Sawadogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 95,
                'views_count' => 1250,
                'is_featured' => true,
            ],
            [
                'nom' => 'Traoré',
                'signification' => 'Nom mandé signifiant "héritier" ou "successeur"',
                'origine' => 'Empire du Mali',
                'histoire' => 'Patronyme très répandu au Burkina Faso, hérité de l\'empire du Mali. Les Traoré sont traditionnellement des chefs de guerre et des administrateurs. Présent dans toutes les régions du pays.',
                'region' => 'Hauts-Bassins',
                'province' => 'Houet',
                'commune' => 'Bobo-Dioulasso',
                'groupe_ethnique' => 'Mandé',
                'langue' => 'Dioula',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Lion',
                'justification_totem' => 'Le lion symbolise la force et le courage des guerriers',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Ouédraogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 98,
                'views_count' => 2100,
                'is_featured' => true,
            ],
            [
                'nom' => 'Sawadogo',
                'signification' => 'Nom mossi signifiant "chef de la terre" ou "maître du sol"',
                'origine' => 'Royaume Mossi (Ouagadougou)',
                'histoire' => 'Patronyme des rois mossi de Ouagadougou. Les Sawadogo sont traditionnellement les gardiens de la terre et les chefs religieux. Nom très respecté dans la société mossi.',
                'region' => 'Centre',
                'province' => 'Kadiogo',
                'commune' => 'Ouagadougou',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Buffle',
                'justification_totem' => 'Le buffle symbolise la force de la terre et de l\'agriculture',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Ouédraogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 92,
                'views_count' => 1800,
                'is_featured' => true,
            ],
            [
                'nom' => 'Kabré',
                'signification' => 'Nom gourmantché signifiant "grand guerrier"',
                'origine' => 'Royaume Gourmantché',
                'histoire' => 'Patronyme des chefs guerriers gourmantché. Les Kabré sont traditionnellement des protecteurs et des défenseurs de leur peuple. Nom très répandu dans l\'Est du Burkina Faso.',
                'region' => 'Est',
                'province' => 'Gourma',
                'commune' => 'Fada N\'Gourma',
                'groupe_ethnique' => 'Gourmantché',
                'langue' => 'Gourmantché',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Éléphant',
                'justification_totem' => 'L\'éléphant symbolise la force et la sagesse du guerrier',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Zongo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 88,
                'views_count' => 1450,
                'is_featured' => true,
            ],
            [
                'nom' => 'Zongo',
                'signification' => 'Nom mossi signifiant "chef de guerre" ou "commandant"',
                'origine' => 'Royaume Mossi',
                'histoire' => 'Patronyme des chefs de guerre mossi. Les Zongo sont traditionnellement des commandants militaires et des protecteurs du royaume. Nom très respecté dans la hiérarchie mossi.',
                'region' => 'Plateau-Central',
                'province' => 'Oubritenga',
                'commune' => 'Ziniaré',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Aigle',
                'justification_totem' => 'L\'aigle symbolise la vision et la stratégie militaire',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Kabré',
                'transmission' => 'Père en fils/fille',
                'frequence' => 85,
                'views_count' => 1200,
                'is_featured' => true,
            ],
            [
                'nom' => 'Tankoano',
                'signification' => 'Nom mossi signifiant "celui qui ne recule jamais"',
                'origine' => 'Royaume Mossi (Tenkodogo)',
                'histoire' => 'Patronyme des rois mossi de Tenkodogo. Les Tankoano sont réputés pour leur courage et leur détermination. Nom porté par de nombreux chefs traditionnels mossi.',
                'region' => 'Centre-Est',
                'province' => 'Boulgou',
                'commune' => 'Tenkodogo',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Buffle',
                'justification_totem' => 'Le buffle symbolise la ténacité et la force',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Sawadogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 82,
                'views_count' => 1100,
                'is_featured' => true,
            ],
            [
                'nom' => 'Kaboré',
                'signification' => 'Nom mossi signifiant "chef spirituel" ou "guide religieux"',
                'origine' => 'Royaume Mossi',
                'histoire' => 'Patronyme des chefs religieux mossi. Les Kaboré sont traditionnellement les gardiens de la tradition spirituelle et les intermédiaires avec les ancêtres.',
                'region' => 'Centre-Nord',
                'province' => 'Sanmatenga',
                'commune' => 'Kaya',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Serpent',
                'justification_totem' => 'Le serpent symbolise la sagesse et la connexion spirituelle',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Ouédraogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 78,
                'views_count' => 950,
                'is_featured' => false,
            ],
            [
                'nom' => 'Bationo',
                'signification' => 'Nom mossi signifiant "chef de la pluie" ou "maître des eaux"',
                'origine' => 'Royaume Mossi',
                'histoire' => 'Patronyme des chefs responsables des rituels de pluie. Les Bationo sont traditionnellement les gardiens de l\'eau et les responsables des cérémonies agricoles.',
                'region' => 'Centre-Ouest',
                'province' => 'Boulkiemdé',
                'commune' => 'Koudougou',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Grenouille',
                'justification_totem' => 'La grenouille est associée à la pluie et à l\'eau',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Sawadogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 75,
                'views_count' => 850,
                'is_featured' => false,
            ],
            [
                'nom' => 'Bamba',
                'signification' => 'Nom mandé signifiant "grand" ou "imposant"',
                'origine' => 'Empire du Mali',
                'histoire' => 'Patronyme des nobles mandé. Les Bamba sont traditionnellement des personnalités importantes dans la société mandé, souvent des chefs de village ou des conseillers.',
                'region' => 'Hauts-Bassins',
                'province' => 'Tuy',
                'commune' => 'Houndé',
                'groupe_ethnique' => 'Mandé',
                'langue' => 'Dioula',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Baobab',
                'justification_totem' => 'Le baobab symbolise la grandeur et la longévité',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Traoré',
                'transmission' => 'Père en fils/fille',
                'frequence' => 72,
                'views_count' => 780,
                'is_featured' => false,
            ],
            [
                'nom' => 'Ouedraogo',
                'signification' => 'Variante orthographique de Ouédraogo',
                'origine' => 'Royaume Mossi (Yatenga)',
                'histoire' => 'Variante orthographique du nom royal Ouédraogo. Même signification et histoire que Ouédraogo, mais avec une orthographe différente.',
                'region' => 'Nord',
                'province' => 'Passoré',
                'commune' => 'Yako',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Cheval',
                'justification_totem' => 'Le cheval est l\'animal totem car le fondateur est arrivé à cheval',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Sawadogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 90,
                'views_count' => 1150,
                'is_featured' => true,
            ],
            [
                'nom' => 'Ouattara',
                'signification' => 'Nom mandé signifiant "chef de guerre"',
                'origine' => 'Empire du Mali',
                'histoire' => 'Patronyme des chefs de guerre mandé. Les Ouattara sont traditionnellement des commandants militaires et des protecteurs de leur communauté.',
                'region' => 'Hauts-Bassins',
                'province' => 'Kénédougou',
                'commune' => 'Orodara',
                'groupe_ethnique' => 'Mandé',
                'langue' => 'Dioula',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Lion',
                'justification_totem' => 'Le lion symbolise la force et le courage du guerrier',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Traoré',
                'transmission' => 'Père en fils/fille',
                'frequence' => 68,
                'views_count' => 720,
                'is_featured' => false,
            ],
            [
                'nom' => 'Zerbo',
                'signification' => 'Nom mossi signifiant "chef de la terre"',
                'origine' => 'Royaume Mossi',
                'histoire' => 'Patronyme des chefs responsables de la terre et de l\'agriculture. Les Zerbo sont traditionnellement les gardiens de la fertilité du sol.',
                'region' => 'Centre-Sud',
                'province' => 'Nahouri',
                'commune' => 'Pô',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Terre',
                'justification_totem' => 'La terre est l\'élément totem car ils en sont les gardiens',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Sawadogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 65,
                'views_count' => 680,
                'is_featured' => false,
            ],
            [
                'nom' => 'Compaoré',
                'signification' => 'Nom mossi signifiant "chef de guerre" ou "commandant"',
                'origine' => 'Royaume Mossi',
                'histoire' => 'Patronyme des chefs de guerre mossi. Les Compaoré sont traditionnellement des commandants militaires et des protecteurs du royaume.',
                'region' => 'Centre',
                'province' => 'Kadiogo',
                'commune' => 'Ouagadougou',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Lion',
                'justification_totem' => 'Le lion symbolise la force et le courage du guerrier',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Ouédraogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 62,
                'views_count' => 650,
                'is_featured' => false,
            ],
            [
                'nom' => 'Kinda',
                'signification' => 'Nom gourmantché signifiant "chef spirituel"',
                'origine' => 'Royaume Gourmantché',
                'histoire' => 'Patronyme des chefs spirituels gourmantché. Les Kinda sont traditionnellement les gardiens de la tradition religieuse et les intermédiaires avec le monde spirituel.',
                'region' => 'Est',
                'province' => 'Gnagna',
                'commune' => 'Bogandé',
                'groupe_ethnique' => 'Gourmantché',
                'langue' => 'Gourmantché',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Serpent',
                'justification_totem' => 'Le serpent symbolise la sagesse et la connexion spirituelle',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Kabré',
                'transmission' => 'Père en fils/fille',
                'frequence' => 58,
                'views_count' => 580,
                'is_featured' => false,
            ],
            [
                'nom' => 'Boro',
                'signification' => 'Nom bissa signifiant "chef" ou "leader"',
                'origine' => 'Royaume Bissa',
                'histoire' => 'Patronyme des chefs bissa. Les Boro sont traditionnellement des leaders et des protecteurs de leur communauté.',
                'region' => 'Centre-Est',
                'province' => 'Koulpélogo',
                'commune' => 'Ouargaye',
                'groupe_ethnique' => 'Bissa',
                'langue' => 'Bissa',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Éléphant',
                'justification_totem' => 'L\'éléphant symbolise la force et la sagesse du leader',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Traoré',
                'transmission' => 'Père en fils/fille',
                'frequence' => 55,
                'views_count' => 520,
                'is_featured' => false,
            ],
            [
                'nom' => 'Sawadogo',
                'signification' => 'Nom mossi signifiant "chef de la terre"',
                'origine' => 'Royaume Mossi (Ouagadougou)',
                'histoire' => 'Patronyme des rois mossi de Ouagadougou. Les Sawadogo sont traditionnellement les gardiens de la terre et les chefs religieux.',
                'region' => 'Centre',
                'province' => 'Kadiogo',
                'commune' => 'Saaba',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Bufflе',
                'justification_totem' => 'Le buffle symbolise la force de la terre et de l\'agriculture',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Ouédraogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 92,
                'views_count' => 1800,
                'is_featured' => true,
            ],
            [
                'nom' => 'Yaméogo',
                'signification' => 'Nom mossi signifiant "chef de la guerre"',
                'origine' => 'Royaume Mossi',
                'histoire' => 'Patronyme des chefs de guerre mossi. Les Yaméogo sont traditionnellement des commandants militaires et des protecteurs du royaume.',
                'region' => 'Plateau-Central',
                'province' => 'Ganzourgou',
                'commune' => 'Zorgho',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Lion',
                'justification_totem' => 'Le lion symbolise la force et le courage du guerrier',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Sawadogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 52,
                'views_count' => 480,
                'is_featured' => false,
            ],
            [
                'nom' => 'Bado',
                'signification' => 'Nom gourmantché signifiant "chef de la terre"',
                'origine' => 'Royaume Gourmantché',
                'histoire' => 'Patronyme des chefs responsables de la terre gourmantché. Les Bado sont traditionnellement les gardiens de la fertilité du sol.',
                'region' => 'Est',
                'province' => 'Tapoa',
                'commune' => 'Diapaga',
                'groupe_ethnique' => 'Gourmantché',
                'langue' => 'Gourmantché',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Terre',
                'justification_totem' => 'La terre est l\'élément totem car ils en sont les gardiens',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Kabré',
                'transmission' => 'Père en fils/fille',
                'frequence' => 48,
                'views_count' => 420,
                'is_featured' => false,
            ],
            [
                'nom' => 'Kaboré',
                'signification' => 'Nom mossi signifiant "chef spirituel"',
                'origine' => 'Royaume Mossi',
                'histoire' => 'Patronyme des chefs religieux mossi. Les Kaboré sont traditionnellement les gardiens de la tradition spirituelle.',
                'region' => 'Centre-Nord',
                'province' => 'Bam',
                'commune' => 'Kongoussi',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Serpent',
                'justification_totem' => 'Le serpent symbolise la sagesse et la connexion spirituelle',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Ouédraogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 78,
                'views_count' => 950,
                'is_featured' => false,
            ],
            [
                'nom' => 'Ouédraogo',
                'signification' => 'Nom royal mossi signifiant "cheval de guerre"',
                'origine' => 'Royaume Mossi (Yatenga)',
                'histoire' => 'Patronyme des rois mossi du Yatenga. Le premier roi Ouédraogo aurait été nommé ainsi car il est arrivé à cheval.',
                'region' => 'Nord',
                'province' => 'Loroum',
                'commune' => 'Titao',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Cheval',
                'justification_totem' => 'Le cheval est l\'animal totem car le fondateur est arrivé à cheval',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Sawadogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 95,
                'views_count' => 1250,
                'is_featured' => true,
            ],
            [
                'nom' => 'Traoré',
                'signification' => 'Nom mandé signifiant "héritier" ou "successeur"',
                'origine' => 'Empire du Mali',
                'histoire' => 'Patronyme très répandu au Burkina Faso, hérité de l\'empire du Mali. Les Traoré sont traditionnellement des chefs de guerre.',
                'region' => 'Hauts-Bassins',
                'province' => 'Houet',
                'commune' => 'Bobo-Dioulasso',
                'groupe_ethnique' => 'Mandé',
                'langue' => 'Dioula',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Lion',
                'justification_totem' => 'Le lion symbolise la force et le courage des guerriers',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Ouédraogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 98,
                'views_count' => 2100,
                'is_featured' => true,
            ],
            [
                'nom' => 'Sawadogo',
                'signification' => 'Nom mossi signifiant "chef de la terre"',
                'origine' => 'Royaume Mossi (Ouagadougou)',
                'histoire' => 'Patronyme des rois mossi de Ouagadougou. Les Sawadogo sont traditionnellement les gardiens de la terre.',
                'region' => 'Centre',
                'province' => 'Kadiogo',
                'commune' => 'Komsilga',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Bufflе',
                'justification_totem' => 'Le buffle symbolise la force de la terre et de l\'agriculture',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Ouédraogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 92,
                'views_count' => 1800,
                'is_featured' => true,
            ],
            [
                'nom' => 'Kabré',
                'signification' => 'Nom gourmantché signifiant "grand guerrier"',
                'origine' => 'Royaume Gourmantché',
                'histoire' => 'Patronyme des chefs guerriers gourmantché. Les Kabré sont traditionnellement des protecteurs et des défenseurs.',
                'region' => 'Est',
                'province' => 'Gourma',
                'commune' => 'Fada N\'Gourma',
                'groupe_ethnique' => 'Gourmantché',
                'langue' => 'Gourmantché',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Éléphant',
                'justification_totem' => 'L\'éléphant symbolise la force et la sagesse du guerrier',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Zongo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 88,
                'views_count' => 1450,
                'is_featured' => true,
            ],
            [
                'nom' => 'Zongo',
                'signification' => 'Nom mossi signifiant "chef de guerre"',
                'origine' => 'Royaume Mossi',
                'histoire' => 'Patronyme des chefs de guerre mossi. Les Zongo sont traditionnellement des commandants militaires.',
                'region' => 'Plateau-Central',
                'province' => 'Kourwéogo',
                'commune' => 'Boussé',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Aigle',
                'justification_totem' => 'L\'aigle symbolise la vision et la stratégie militaire',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Kabré',
                'transmission' => 'Père en fils/fille',
                'frequence' => 85,
                'views_count' => 1200,
                'is_featured' => true,
            ],
            [
                'nom' => 'Tankoano',
                'signification' => 'Nom mossi signifiant "celui qui ne recule jamais"',
                'origine' => 'Royaume Mossi (Tenkodogo)',
                'histoire' => 'Patronyme des rois mossi de Tenkodogo. Les Tankoano sont réputés pour leur courage et leur détermination.',
                'region' => 'Centre-Est',
                'province' => 'Kouritenga',
                'commune' => 'Koupéla',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Bufflе',
                'justification_totem' => 'Le buffle symbolise la ténacité et la force',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Sawadogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 82,
                'views_count' => 1100,
                'is_featured' => true,
            ],
            [
                'nom' => 'Bationo',
                'signification' => 'Nom mossi signifiant "chef de la pluie"',
                'origine' => 'Royaume Mossi',
                'histoire' => 'Patronyme des chefs responsables des rituels de pluie. Les Bationo sont traditionnellement les gardiens de l\'eau.',
                'region' => 'Centre-Ouest',
                'province' => 'Sanguié',
                'commune' => 'Réo',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Grenouille',
                'justification_totem' => 'La grenouille est associée à la pluie et à l\'eau',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Sawadogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 75,
                'views_count' => 850,
                'is_featured' => false,
            ],
            [
                'nom' => 'Bamba',
                'signification' => 'Nom mandé signifiant "grand" ou "imposant"',
                'origine' => 'Empire du Mali',
                'histoire' => 'Patronyme des nobles mandé. Les Bamba sont traditionnellement des personnalités importantes dans la société mandé.',
                'region' => 'Hauts-Bassins',
                'province' => 'Houet',
                'commune' => 'Bobo-Dioulasso',
                'groupe_ethnique' => 'Mandé',
                'langue' => 'Dioula',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Baobab',
                'justification_totem' => 'Le baobab symbolise la grandeur et la longévité',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Traoré',
                'transmission' => 'Père en fils/fille',
                'frequence' => 72,
                'views_count' => 780,
                'is_featured' => false,
            ],
            [
                'nom' => 'Ouattara',
                'signification' => 'Nom mandé signifiant "chef de guerre"',
                'origine' => 'Empire du Mali',
                'histoire' => 'Patronyme des chefs de guerre mandé. Les Ouattara sont traditionnellement des commandants militaires.',
                'region' => 'Hauts-Bassins',
                'province' => 'Kénédougou',
                'commune' => 'Sindou',
                'groupe_ethnique' => 'Mandé',
                'langue' => 'Dioula',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Lion',
                'justification_totem' => 'Le lion symbolise la force et le courage du guerrier',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Traoré',
                'transmission' => 'Père en fils/fille',
                'frequence' => 68,
                'views_count' => 720,
                'is_featured' => false,
            ],
            [
                'nom' => 'Zerbo',
                'signification' => 'Nom mossi signifiant "chef de la terre"',
                'origine' => 'Royaume Mossi',
                'histoire' => 'Patronyme des chefs responsables de la terre et de l\'agriculture. Les Zerbo sont traditionnellement les gardiens de la fertilité du sol.',
                'region' => 'Centre-Sud',
                'province' => 'Bazèga',
                'commune' => 'Kombissiri',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Terre',
                'justification_totem' => 'La terre est l\'élément totem car ils en sont les gardiens',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Sawadogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 65,
                'views_count' => 680,
                'is_featured' => false,
            ],
            [
                'nom' => 'Compaoré',
                'signification' => 'Nom mossi signifiant "chef de guerre"',
                'origine' => 'Royaume Mossi',
                'histoire' => 'Patronyme des chefs de guerre mossi. Les Compaoré sont traditionnellement des commandants militaires.',
                'region' => 'Centre',
                'province' => 'Kadiogo',
                'commune' => 'Pabré',
                'groupe_ethnique' => 'Mossi',
                'langue' => 'Mooré',
                'patronyme_sexe' => 'oui',
                'patronyme_sexe_detail' => null,
                'totem' => 'Lion',
                'justification_totem' => 'Le lion symbolise la force et le courage du guerrier',
                'parents_plaisanterie' => 'Cousinage à plaisanterie avec les Ouédraogo',
                'transmission' => 'Père en fils/fille',
                'frequence' => 62,
                'views_count' => 650,
                'is_featured' => false,
            ],
        ];

        foreach ($patronymesData as $patronymeData) {
            // Get related models
            $region = Region::where('nom', $patronymeData['region'])->first();
            $province = null;
            $commune = null;
            $groupeEthnique = null;
            $langue = null;
            $modeTransmission = null;

            if ($region) {
                $province = Province::where('nom', $patronymeData['province'])->where('region_id', $region->id)->first();
                if ($province) {
                    $commune = Commune::where('nom', $patronymeData['commune'])->where('province_id', $province->id)->first();
                }
            }

            $groupeEthnique = GroupeEthnique::where('nom', $patronymeData['groupe_ethnique'])->first();
            $langue = Langue::where('nom', $patronymeData['langue'])->first();
            $modeTransmission = ModeTransmission::where('type', $patronymeData['transmission'])->first();

            // Create patronyme
            Patronyme::create([
                'nom' => $patronymeData['nom'],
                'signification' => $patronymeData['signification'],
                'origine' => $patronymeData['origine'],
                'histoire' => $patronymeData['histoire'],
                'region_id' => $region ? $region->id : null,
                'province_id' => $province ? $province->id : null,
                'commune_id' => $commune ? $commune->id : null,
                'groupe_ethnique_id' => $groupeEthnique ? $groupeEthnique->id : null,
                'langue_id' => $langue ? $langue->id : null,
                'mode_transmission_id' => $modeTransmission ? $modeTransmission->id : null,
                'patronyme_sexe' => $patronymeData['patronyme_sexe'],
                'patronyme_sexe_detail' => $patronymeData['patronyme_sexe_detail'],
                'totem' => $patronymeData['totem'],
                'justification_totem' => $patronymeData['justification_totem'],
                'parents_plaisanterie' => $patronymeData['parents_plaisanterie'],
                'frequence' => $patronymeData['frequence'],
                'views_count' => $patronymeData['views_count'],
                'is_featured' => $patronymeData['is_featured'],
                'date_collecte' => Carbon::now()->subDays(rand(1, 365)),
                'collecteur' => 'Enquêteur ' . rand(1, 10),
                'code_fiche' => 'BF' . str_pad(rand(1, 9999), 4, '0', STR_PAD_LEFT),
                'enquete_nom' => 'Informateur ' . rand(1, 100),
                'enquete_age' => rand(25, 80),
                'enquete_sexe' => rand(0, 1) ? 'M' : 'F',
                'enquete_fonction' => ['Chef traditionnel', 'Griot', 'Agriculteur', 'Artisan', 'Commerçant'][rand(0, 4)],
                'enquete_telephone' => '+226' . rand(70000000, 79999999),
                'enquete_email' => 'enquete' . rand(1, 100) . '@example.bf',
            ]);
        }

        $this->command->info('30 patronymes réels du Burkina Faso créés avec succès !');
    }
}
