version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=patronymes
      - DB_USERNAME=patronymes
      - DB_PASSWORD=password
    depends_on:
      - db
    volumes:
      - ./storage:/var/www/storage

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=patronymes
      - POSTGRES_USER=patronymes
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
